#!/usr/bin/python3

import os
import sys
import cgi
import cgitb
from datetime import datetime

# Enable CGI error reporting
cgitb.enable()

# Print HTTP headers
print("Content-Type: text/html")
print()

# HTML response
print("""<!DOCTYPE html>
<html>
<head>
    <title>Python CGI Test</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; }}
        .info {{ background: #f0f0f0; padding: 10px; margin: 10px 0; }}
        .env {{ background: #e8f4f8; padding: 10px; margin: 10px 0; }}
        table {{ border-collapse: collapse; width: 100%; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        th {{ background-color: #f2f2f2; }}
    </style>
</head>
<body>
    <h1>🐍 Python CGI Test - Success!</h1>
    <div class="info">
        <h2>Server Information</h2>
        <p><strong>Date/Time:</strong> {}</p>
        <p><strong>Python Version:</strong> {}</p>
        <p><strong>Script Path:</strong> {}</p>
    </div>
    
    <div class="env">
        <h2>CGI Environment Variables</h2>
        <table>
            <tr><th>Variable</th><th>Value</th></tr>""".format(
    datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    sys.version,
    os.path.abspath(__file__)
))

# Display relevant environment variables
cgi_vars = [
    'REQUEST_METHOD', 'CONTENT_TYPE', 'CONTENT_LENGTH', 'PATH_INFO',
    'QUERY_STRING', 'SERVER_PROTOCOL', 'GATEWAY_INTERFACE', 'SERVER_NAME',
    'SERVER_PORT', 'HTTP_HOST', 'HTTP_USER_AGENT'
]

for var in cgi_vars:
    value = os.environ.get(var, 'Not set')
    print(f"            <tr><td>{var}</td><td>{value}</td></tr>")

print("""        </table>
    </div>
    
    <div class="info">
        <h2>Request Information</h2>
        <p><strong>Method:</strong> {}</p>
        <p><strong>Content Length:</strong> {}</p>
    </div>""".format(
    os.environ.get('REQUEST_METHOD', 'Unknown'),
    os.environ.get('CONTENT_LENGTH', '0')
))

# If POST request, read and display the body
if os.environ.get('REQUEST_METHOD') == 'POST':
    content_length = int(os.environ.get('CONTENT_LENGTH', '0'))
    if content_length > 0:
        post_data = sys.stdin.read(content_length)
        print(f"""    <div class="env">
        <h2>POST Data</h2>
        <pre>{post_data}</pre>
    </div>""")

print("""    
    <div class="info">
        <h2>Test Results</h2>
        <p>✅ CGI script executed successfully</p>
        <p>✅ Environment variables are set</p>
        <p>✅ HTML output is working</p>
        <p>✅ Python CGI integration is functional</p>
    </div>
    
    <hr>
    <p><em>Generated by webserv Python CGI</em></p>
</body>
</html>""")