#!/usr/bin/python3

import os
import sys
import platform
import socket
import time
from datetime import datetime

# Print HTTP headers
print("Content-Type: text/html")
print()

# HTML response
print("""<!DOCTYPE html>
<html>
<head>
    <title> WebServ 42 - System Information</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; background: #f8f9fa; }}
        .container {{ max-width: 900px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
        h1 {{ color: #2563eb; border-bottom: 3px solid #2563eb; padding-bottom: 10px; }}
        h2 {{ color: #1f2937; margin-top: 30px; }}
        .info-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; }}
        .info-card {{ background: #f8fafc; padding: 20px; border-radius: 8px; border-left: 4px solid #2563eb; }}
        .info-card h3 {{ margin: 0 0 15px 0; color: #1f2937; }}
        .info-item {{ display: flex; justify-content: space-between; margin: 8px 0; }}
        .info-label {{ font-weight: bold; color: #374151; }}
        .info-value {{ color: #6b7280; font-family: monospace; }}
        .status-ok {{ color: #10b981; font-weight: bold; }}
        .status-info {{ color: #3b82f6; font-weight: bold; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ border: 1px solid #e5e7eb; padding: 12px; text-align: left; }}
        th {{ background: #f3f4f6; font-weight: 600; }}
        .highlight {{ background: #fef3c7; padding: 2px 6px; border-radius: 4px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🖥️ WebServ 42 - System Information</h1>
        <p>Real-time system information generated by Python CGI script</p>
        
        <div class="info-grid">
            <div class="info-card">
                <h3>Server Information</h3>
                <div class="info-item">
                    <span class="info-label">Server:</span>
                    <span class="info-value status-ok">WebServ 42</span>
                </div>
                <div class="info-item">
                    <span class="info-label">HTTP Version:</span>
                    <span class="info-value">HTTP/1.1</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Gateway:</span>
                    <span class="info-value">{gateway}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Protocol:</span>
                    <span class="info-value">{protocol}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Server Port:</span>
                    <span class="info-value">{port}</span>
                </div>
            </div>
            
            <div class="info-card">
                <h3>System Information</h3>
                <div class="info-item">
                    <span class="info-label">OS:</span>
                    <span class="info-value">{system}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Platform:</span>
                    <span class="info-value">{platform_info}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Architecture:</span>
                    <span class="info-value">{architecture}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Hostname:</span>
                    <span class="info-value">{hostname}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Python Version:</span>
                    <span class="info-value">{python_version}</span>
                </div>
            </div>
            
            <div class="info-card">
                <h3>Request Information</h3>
                <div class="info-item">
                    <span class="info-label">Method:</span>
                    <span class="info-value status-info">{method}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">URI:</span>
                    <span class="info-value">{uri}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Query String:</span>
                    <span class="info-value">{query}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Remote Address:</span>
                    <span class="info-value">{remote_addr}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">User Agent:</span>
                    <span class="info-value">{user_agent}</span>
                </div>
            </div>
            
            <div class="info-card">
                <h3>Timing Information</h3>
                <div class="info-item">
                    <span class="info-label">Current Time:</span>
                    <span class="info-value">{current_time}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Uptime:</span>
                    <span class="info-value">{uptime}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Process ID:</span>
                    <span class="info-value">{pid}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Parent PID:</span>
                    <span class="info-value">{ppid}</span>
                </div>
            </div>
        </div>
        
        <h2>Environment Variables</h2>
        <table>
            <tr><th>Variable</th><th>Value</th></tr>""".format(
    gateway=os.environ.get('GATEWAY_INTERFACE', 'Not set'),
    protocol=os.environ.get('SERVER_PROTOCOL', 'Not set'),
    port=os.environ.get('SERVER_PORT', 'Not set'),
    system=platform.system(),
    platform_info=platform.platform(),
    architecture=platform.machine(),
    hostname=socket.gethostname(),
    python_version=platform.python_version(),
    method=os.environ.get('REQUEST_METHOD', 'Not set'),
    uri=os.environ.get('REQUEST_URI', 'Not set'),
    query=os.environ.get('QUERY_STRING', 'Not set'),
    remote_addr=os.environ.get('REMOTE_ADDR', 'Not set'),
    user_agent=os.environ.get('HTTP_USER_AGENT', 'Not set'),
    current_time=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    uptime=f"{time.time():.2f} seconds",
    pid=os.getpid(),
    ppid=os.getppid()
))

# Display relevant environment variables
important_vars = [
    'REQUEST_METHOD', 'REQUEST_URI', 'QUERY_STRING', 'SERVER_PROTOCOL',
    'SERVER_NAME', 'SERVER_PORT', 'GATEWAY_INTERFACE', 'CONTENT_TYPE',
    'CONTENT_LENGTH', 'HTTP_HOST', 'HTTP_USER_AGENT', 'HTTP_ACCEPT',
    'HTTP_ACCEPT_ENCODING', 'HTTP_ACCEPT_LANGUAGE', 'HTTP_CONNECTION',
    'REMOTE_ADDR', 'REMOTE_HOST', 'SCRIPT_NAME', 'PATH_INFO'
]

for var in important_vars:
    value = os.environ.get(var, '<em>Not set</em>')
    if len(str(value)) > 80:
        value = str(value)[:80] + '...'
    print(f'            <tr><td><strong>{var}</strong></td><td>{value}</td></tr>')

print("""        </table>
        
        <h2>CGI Test Results</h2>
        <div class="info-grid">
            <div class="info-card">
                <h3>✅ Test Status</h3>
                <div class="info-item">
                    <span class="info-label">CGI Execution:</span>
                    <span class="info-value status-ok">Working</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Environment Variables:</span>
                    <span class="info-value status-ok">Available</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Python Interpreter:</span>
                    <span class="info-value status-ok">Functional</span>
                </div>
                <div class="info-item">
                    <span class="info-label">System Integration:</span>
                    <span class="info-value status-ok">Complete</span>
                </div>
            </div>
        </div>
        
        <p style="margin-top: 30px; text-align: center; color: #6b7280;">
            <strong>WebServ 42</strong> - Generated at {generation_time}
        </p>
        
        <p style="text-align: center;">
            <a href="/" style="color: #2563eb; text-decoration: none;">← Back to Main Page</a>
        </p>
    </div>
</body>
</html>""".format(
    generation_time=datetime.now().strftime('%Y-%m-%d %H:%M:%S')
))